import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { BoardSummary } from '@shared/types/board'
import type { PlacedDevice, WireConnection } from '@shared/types/project'
import { validatePinAssignment, findAvailablePin } from '@shared/boards/wiringEngine'
import type { LanguageCode } from '@renderer/lib/i18n/translations'

// ─────────────────────────────────────────────────────────────────────────────
// State Shape
// ─────────────────────────────────────────────────────────────────────────────
export interface AppState {
  // ── Board ─────────────────────────────────────────────────────────────────
  /** All boards returned from the main process (loaded on app start) */
  availableBoards: BoardSummary[]
  /** The currently selected board */
  selectedBoard: BoardSummary | null

  // ── UI State ──────────────────────────────────────────────────────────────
  /** Active center panel tab */
  activeTab: 'blocks' | 'hardware' | 'ai' | 'simulator'
  /** Active right panel tab */
  activeRightTab: 'code' | 'connections' | 'monitor'
  /** App chrome language — persisted across sessions. */
  language: LanguageCode

  // ── Hardware Canvas ───────────────────────────────────────────────────────
  /** Layouts for each board ID (devices and wires) */
  boardLayouts: Record<string, { devices: PlacedDevice[], wires: WireConnection[] }>
  
  /** Currently selected item in the hardware canvas */
  selectedItemId: string | null

  // ── Project ───────────────────────────────────────────────────────────────
  /** Current project name */
  projectName: string
  /** Path of the last saved .edublock file (null = unsaved) */
  savedFilePath: string | null
  /** True if there are unsaved changes */
  isDirty: boolean

  // ── Upload / Serial ───────────────────────────────────────────────────────
  /** Active COM port selected in the upload toolbar */
  activeComPort: string | null
  /** True while a compile/upload operation is running */
  isUploading: boolean
  /** True while the toolbar's serial port is open — gates the AI panel's streaming control */
  isSerialConnected: boolean

  // ── Blockly ───────────────────────────────────────────────────────────────
  /** Serialized Blockly workspace state */
  blocklyWorkspaceJson: Record<string, any> | null

  // ── Code Generation ───────────────────────────────────────────────────────
  /** The latest generated C++ code */
  generatedCode: string
  /** Any warnings generated by the compiler/generator */
  warnings: string[]
  /**
   * True once the user has hand-edited the Code panel directly. While true,
   * GeneratorObserver stops overwriting generatedCode from the Blockly
   * workspace — otherwise the next block/hardware change would silently
   * wipe out manual edits.
   */
  isCodeManuallyEdited: boolean

  // ── Dialogs ───────────────────────────────────────────────────────────────
  promptConfig: {
    isOpen: boolean
    message: string
    defaultValue: string
    callback: ((value: string | null) => void) | null
  } | null

  // ── Project Feedback ──────────────────────────────────────────────────────
  /** Status message for save operations */
  saveStatus: string | null
  /** Timestamp updated when a project is explicitly loaded to force Blockly resync */
  projectLoadTimestamp: number
}

// ─────────────────────────────────────────────────────────────────────────────
// Actions Shape
// ─────────────────────────────────────────────────────────────────────────────
export interface AppActions {
  // Board actions
  setAvailableBoards: (boards: BoardSummary[]) => void
  setBoard: (boardId: string) => void
  
  // UI Actions
  setActiveTab: (tab: 'blocks' | 'hardware' | 'ai') => void
  setActiveRightTab: (tab: 'code' | 'connections' | 'monitor') => void
  setLanguage: (lang: LanguageCode) => void

  // Hardware canvas actions
  addDevice: (device: PlacedDevice) => void
  removeDevice: (deviceId: string) => void
  updateDevicePosition: (deviceId: string, x: number, y: number) => void
  updateDevicePin: (deviceId: string, pin: string) => void
  autoWireUnassignedDevices: () => void
  clearDevices: () => void

  addWire: (wire: WireConnection) => void
  removeWire: (wireId: string) => void
  setSelectedItemId: (id: string | null) => void

  // Project actions
  setProjectName: (name: string) => void
  setSavedFilePath: (path: string | null) => void
  markClean: () => void
  markDirty: () => void

  // Upload / serial actions
  setActiveComPort: (port: string | null) => void
  setIsUploading: (uploading: boolean) => void
  setIsSerialConnected: (connected: boolean) => void

  // Blockly actions
  setBlocklyWorkspaceJson: (json: Record<string, any> | null) => void

  // Code Generation
  setGeneratedCode: (code: string) => void
  setWarnings: (warnings: string[]) => void
  /** Hand-edit the Code panel directly — takes over from the Blockly-generated code. */
  setManualCode: (code: string) => void
  /** Discards manual edits and resumes generating code from the Blockly workspace. */
  resyncCodeFromBlocks: () => void

  // Dialogs
  setPromptConfig: (config: AppState['promptConfig']) => void
  setSaveStatus: (status: string | null) => void

  // Full reset (e.g., "New Project")
  resetProject: () => void
  loadProject: (data: any) => void
}

// ─────────────────────────────────────────────────────────────────────────────
// Initial state
// ─────────────────────────────────────────────────────────────────────────────
const initialState: AppState = {
  availableBoards: [],
  selectedBoard: null,
  activeTab: 'blocks',
  activeRightTab: 'code',
  language: 'en',
  boardLayouts: {},
  selectedItemId: null,
  projectName: 'Untitled Project',
  savedFilePath: null,
  isDirty: false,
  activeComPort: null,
  isUploading: false,
  isSerialConnected: false,
  blocklyWorkspaceJson: null,
  generatedCode: '',
  warnings: [],
  isCodeManuallyEdited: false,
  promptConfig: null,
  saveStatus: null,
  projectLoadTimestamp: 0,
}

// ─────────────────────────────────────────────────────────────────────────────
// Store
// ─────────────────────────────────────────────────────────────────────────────
export const useAppStore = create<AppState & AppActions>()(
  persist(
    (set, get) => ({
      ...initialState,

      // ── Board ───────────────────────────────────────────────────────────
      setAvailableBoards: (boards) =>
        set({
          availableBoards: boards,
          // Auto-select first board if nothing is selected yet
          selectedBoard: get().selectedBoard ?? boards[0] ?? null,
        }),

      setBoard: (boardId) => {
        const board = get().availableBoards.find(b => b.id === boardId)
        if (!board) {
          console.warn(`[Store] setBoard: unknown board id "${boardId}"`)
          return
        }

        set(state => {
          let newBoardLayouts = { ...state.boardLayouts }
          
          // If a layout exists for this new board, let's validate and remap invalid pins
          const layout = newBoardLayouts[boardId]
          if (layout && layout.devices.length > 0) {
            const updatedDevices = [...layout.devices]
            const seenPins = new Set<string>()
            
            for (let i = 0; i < updatedDevices.length; i++) {
              const device = updatedDevices[i]
              const currentPin = typeof device.mappedPin === 'string' ? device.mappedPin : ''
              
              if (currentPin) {
                const { valid } = validatePinAssignment(device.type, currentPin, boardId)
                if (!valid || seenPins.has(currentPin)) {
                  // Temporarily remove this device's pin so we can find a free one among the others
                  updatedDevices[i] = { ...device, mappedPin: '' }
                  const newPin = findAvailablePin(device.type, boardId, updatedDevices)
                  updatedDevices[i].mappedPin = newPin
                  if (newPin) { if (typeof newPin === 'string') seenPins.add(newPin); else Object.values(newPin).forEach(p => seenPins.add(p)); }
                } else {
                  seenPins.add(currentPin)
                }
              } else {
                // Was completely unassigned
                const newPin = findAvailablePin(device.type, boardId, updatedDevices)
                updatedDevices[i] = { ...device, mappedPin: newPin }
                if (newPin) { if (typeof newPin === 'string') seenPins.add(newPin); else Object.values(newPin).forEach(p => seenPins.add(p)); }
              }
            }
            
            newBoardLayouts[boardId] = {
              ...layout,
              devices: updatedDevices
            }
          }

          return {
            selectedBoard: board,
            selectedItemId: null,
            blocklyWorkspaceJson: null, // Clear workspace when switching boards
            isDirty: true,
            boardLayouts: newBoardLayouts
          }
        })
      },

      // ── UI ──────────────────────────────────────────────────────────────
      setActiveTab: (tab) => set({ activeTab: tab }),
      setActiveRightTab: (tab) => set({ activeRightTab: tab }),
      setLanguage: (lang) => set({ language: lang }),

      // ── Hardware canvas ─────────────────────────────────────────────────
      addDevice: (device) =>
        set(state => {
          if (!state.selectedBoard) return state
          const boardId = state.selectedBoard.id
          const layout = state.boardLayouts[boardId] || { devices: [], wires: [] }
          
          // Auto-assign a pin for this new device
          const assignedPin = findAvailablePin(device.type, boardId, layout.devices)
          
          const deviceWithPin = {
            ...device,
            mappedPin: assignedPin
          }

          return {
            boardLayouts: {
              ...state.boardLayouts,
              [boardId]: { ...layout, devices: [...layout.devices, deviceWithPin] }
            },
            isDirty: true,
          }
        }),

      removeDevice: (deviceId) =>
        set(state => {
          if (!state.selectedBoard) return state
          const boardId = state.selectedBoard.id
          const layout = state.boardLayouts[boardId]
          if (!layout) return state
          return {
            boardLayouts: {
              ...state.boardLayouts,
              [boardId]: { ...layout, devices: layout.devices.filter(d => d.id !== deviceId) }
            },
            isDirty: true,
          }
        }),

      updateDevicePosition: (deviceId, x, y) =>
        set(state => {
          if (!state.selectedBoard) return state
          const boardId = state.selectedBoard.id
          const layout = state.boardLayouts[boardId]
          if (!layout) return state
          return {
            boardLayouts: {
              ...state.boardLayouts,
              [boardId]: {
                ...layout,
                devices: layout.devices.map(d =>
                  d.id === deviceId ? { ...d, canvasX: x, canvasY: y } : d
                )
              }
            },
            isDirty: true,
          }
        }),

      updateDevicePin: (deviceId, pin) =>
        set(state => {
          if (!state.selectedBoard) return state
          const boardId = state.selectedBoard.id
          const layout = state.boardLayouts[boardId]
          if (!layout) return state
          return {
            boardLayouts: {
              ...state.boardLayouts,
              [boardId]: {
                ...layout,
                devices: layout.devices.map(d =>
                  d.id === deviceId ? { ...d, mappedPin: pin } : d
                )
              }
            },
            isDirty: true,
          }
        }),

      autoWireUnassignedDevices: () =>
        set(state => {
          if (!state.selectedBoard) return state
          const boardId = state.selectedBoard.id
          const layout = state.boardLayouts[boardId]
          if (!layout || layout.devices.length === 0) return state

          let hasChanges = false
          const updatedDevices = [...layout.devices]
          const seenPins = new Set<string>()
          
          for (let i = 0; i < updatedDevices.length; i++) {
            const device = updatedDevices[i]
            const currentPin = typeof device.mappedPin === 'string' ? device.mappedPin : ''
            
            let needsNewPin = false
            if (!currentPin) {
              needsNewPin = true
            } else {
              const { valid } = validatePinAssignment(device.type, currentPin, boardId)
              if (!valid || seenPins.has(currentPin)) {
                needsNewPin = true
              }
            }

            if (needsNewPin) {
              updatedDevices[i] = { ...device, mappedPin: '' } // Clear it temporarily
              const newPin = findAvailablePin(device.type, boardId, updatedDevices)
              updatedDevices[i].mappedPin = newPin
              if (newPin) { if (typeof newPin === 'string') seenPins.add(newPin); else Object.values(newPin).forEach(p => seenPins.add(p)); }
              hasChanges = true
            } else {
              seenPins.add(currentPin)
            }
          }

          if (!hasChanges) return state

          return {
            boardLayouts: {
              ...state.boardLayouts,
              [boardId]: {
                ...layout,
                devices: updatedDevices
              }
            },
            isDirty: true,
          }
        }),

      clearDevices: () =>
        set(state => {
          if (!state.selectedBoard) return state
          return {
            boardLayouts: {
              ...state.boardLayouts,
              [state.selectedBoard.id]: { devices: [], wires: [] }
            },
            selectedItemId: null,
            isDirty: true
          }
        }),

      addWire: (wire) =>
        set(state => {
          if (!state.selectedBoard) return state
          const boardId = state.selectedBoard.id
          const layout = state.boardLayouts[boardId] || { devices: [], wires: [] }
          return {
            boardLayouts: {
              ...state.boardLayouts,
              [boardId]: { ...layout, wires: [...layout.wires, wire] }
            },
            isDirty: true,
          }
        }),

      removeWire: (wireId) =>
        set(state => {
          if (!state.selectedBoard) return state
          const boardId = state.selectedBoard.id
          const layout = state.boardLayouts[boardId]
          if (!layout) return state
          return {
            boardLayouts: {
              ...state.boardLayouts,
              [boardId]: { ...layout, wires: layout.wires.filter(w => w.id !== wireId) }
            },
            isDirty: true,
          }
        }),

      setSelectedItemId: (id) =>
        set({ selectedItemId: id }),

      // ── Project ─────────────────────────────────────────────────────────
      setProjectName: (name) =>
        set({ projectName: name, isDirty: true }),

      setSavedFilePath: (path) =>
        set({ savedFilePath: path }),

      markClean: () =>
        set({ isDirty: false }),

      markDirty: () =>
        set({ isDirty: true }),

      // ── Upload / serial ─────────────────────────────────────────────────
      setActiveComPort: (port) =>
        set({ activeComPort: port }),

      setIsUploading: (uploading) =>
        set({ isUploading: uploading }),

      setIsSerialConnected: (connected) =>
        set({ isSerialConnected: connected }),

      setBlocklyWorkspaceJson: (json) =>
        set({ blocklyWorkspaceJson: json, isDirty: true }),

      setGeneratedCode: (code) =>
        set({ generatedCode: code }),

      setWarnings: (warnings) =>
        set({ warnings }),

      setManualCode: (code) =>
        set({ generatedCode: code, isCodeManuallyEdited: true, isDirty: true }),

      resyncCodeFromBlocks: () =>
        set({ isCodeManuallyEdited: false }),

      setPromptConfig: (config) =>
        set({ promptConfig: config }),

      setSaveStatus: (status) =>
        set({ saveStatus: status }),

      // ── Full reset ───────────────────────────────────────────────────────
      resetProject: () =>
        set({
          boardLayouts: {},
          selectedItemId: null,
          projectName: 'Untitled Project',
          savedFilePath: null,
          isDirty: false,
          activeComPort: null,
          isUploading: false,
          blocklyWorkspaceJson: null,
          generatedCode: '',
          warnings: [],
          isCodeManuallyEdited: false,
          projectLoadTimestamp: Date.now(),
        }),

      loadProject: (data) =>
        set((state) => {
          let selectedBoard = state.selectedBoard;
          if (data.selectedBoard) {
            const foundBoard = state.availableBoards.find(b => b.id === data.selectedBoard.id);
            if (foundBoard) selectedBoard = foundBoard;
          }
          return {
            projectName: data.projectName || 'Untitled Project',
            savedFilePath: data.savedFilePath || null,
            blocklyWorkspaceJson: data.blocklyWorkspaceJson || null,
            boardLayouts: data.boardLayouts || {},
            selectedBoard,
            isDirty: false,
            isCodeManuallyEdited: false,
            projectLoadTimestamp: Date.now()
          };
        }),
    }),
    {
      name: 'edublocks-app-state',
      // Only persist user preferences, not transient runtime state
      partialize: (state) => ({
        language: state.language,
        selectedBoard: state.selectedBoard,
        activeComPort: state.activeComPort,
        blocklyWorkspaceJson: state.blocklyWorkspaceJson,
        boardLayouts: state.boardLayouts,
        generatedCode: state.generatedCode,
        isCodeManuallyEdited: state.isCodeManuallyEdited,
        projectName: state.projectName,
        savedFilePath: state.savedFilePath,
        isDirty: state.isDirty,
      }),
    }
  )
)

if (typeof window !== 'undefined') {
  ;(window as any).useAppStore = useAppStore
}

// ─────────────────────────────────────────────────────────────────────────────
// Selectors (derived state helpers)
// ─────────────────────────────────────────────────────────────────────────────
export const selectSelectedBoard = (s: AppState & AppActions) => s.selectedBoard
export const selectPlacedDevices = (s: AppState & AppActions) => s.selectedBoard ? (s.boardLayouts[s.selectedBoard.id]?.devices || []) : []
export const selectWires         = (s: AppState & AppActions) => s.selectedBoard ? (s.boardLayouts[s.selectedBoard.id]?.wires || []) : []
export const selectIsUploading   = (s: AppState & AppActions) => s.isUploading
export const selectIsDirty       = (s: AppState & AppActions) => s.isDirty
